// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Controls when the in-game performance monitor is shown.
type PerformanceMonitor byte

const (
	PerformanceMonitorShowWhenSuboptimal PerformanceMonitor = 0
	PerformanceMonitorAlwaysShow         PerformanceMonitor = 1
	PerformanceMonitorNeverShow          PerformanceMonitor = 2
)

var EnumNamesPerformanceMonitor = map[PerformanceMonitor]string{
	PerformanceMonitorShowWhenSuboptimal: "ShowWhenSuboptimal",
	PerformanceMonitorAlwaysShow:         "AlwaysShow",
	PerformanceMonitorNeverShow:          "NeverShow",
}

var EnumValuesPerformanceMonitor = map[string]PerformanceMonitor{
	"ShowWhenSuboptimal": PerformanceMonitorShowWhenSuboptimal,
	"AlwaysShow":         PerformanceMonitorAlwaysShow,
	"NeverShow":          PerformanceMonitorNeverShow,
}

func (v PerformanceMonitor) String() string {
	if s, ok := EnumNamesPerformanceMonitor[v]; ok {
		return s
	}
	return "PerformanceMonitor(" + strconv.FormatInt(int64(v), 10) + ")"
}
