// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Ping response message
type PingResponseT struct {
	Cookie uint64 `json:"cookie"`
}

func (t *PingResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	PingResponseStart(builder)
	PingResponseAddCookie(builder, t.Cookie)
	return PingResponseEnd(builder)
}

func (rcv *PingResponse) UnPackTo(t *PingResponseT) {
	t.Cookie = rcv.Cookie()
}

func (rcv *PingResponse) UnPack() *PingResponseT {
	if rcv == nil {
		return nil
	}
	t := &PingResponseT{}
	rcv.UnPackTo(t)
	return t
}

type PingResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPingResponse(buf []byte, offset flatbuffers.UOffsetT) *PingResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PingResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPingResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPingResponse(buf []byte, offset flatbuffers.UOffsetT) *PingResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PingResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPingResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PingResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PingResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PingResponse) Cookie() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PingResponse) MutateCookie(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func PingResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PingResponseAddCookie(builder *flatbuffers.Builder, cookie uint64) {
	builder.PrependUint64Slot(0, cookie, 0)
}
func PingResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
