// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type ScoringRuleMutator byte

const (
	ScoringRuleMutatorDefault  ScoringRuleMutator = 0
	ScoringRuleMutatorDisabled ScoringRuleMutator = 1
)

var EnumNamesScoringRuleMutator = map[ScoringRuleMutator]string{
	ScoringRuleMutatorDefault:  "Default",
	ScoringRuleMutatorDisabled: "Disabled",
}

var EnumValuesScoringRuleMutator = map[string]ScoringRuleMutator{
	"Default":  ScoringRuleMutatorDefault,
	"Disabled": ScoringRuleMutatorDisabled,
}

func (v ScoringRuleMutator) String() string {
	if s, ok := EnumNamesScoringRuleMutator[v]; ok {
		return s
	}
	return "ScoringRuleMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
