// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Controls when the in-game performance monitor will display.
type UpdatePerformanceMonitorT struct {
	Show PerformanceMonitor `json:"show"`
}

func (t *UpdatePerformanceMonitorT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	UpdatePerformanceMonitorStart(builder)
	UpdatePerformanceMonitorAddShow(builder, t.Show)
	return UpdatePerformanceMonitorEnd(builder)
}

func (rcv *UpdatePerformanceMonitor) UnPackTo(t *UpdatePerformanceMonitorT) {
	t.Show = rcv.Show()
}

func (rcv *UpdatePerformanceMonitor) UnPack() *UpdatePerformanceMonitorT {
	if rcv == nil {
		return nil
	}
	t := &UpdatePerformanceMonitorT{}
	rcv.UnPackTo(t)
	return t
}

type UpdatePerformanceMonitor struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdatePerformanceMonitor(buf []byte, offset flatbuffers.UOffsetT) *UpdatePerformanceMonitor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdatePerformanceMonitor{}
	x.Init(buf, n+offset)
	return x
}

func FinishUpdatePerformanceMonitorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUpdatePerformanceMonitor(buf []byte, offset flatbuffers.UOffsetT) *UpdatePerformanceMonitor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdatePerformanceMonitor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUpdatePerformanceMonitorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UpdatePerformanceMonitor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdatePerformanceMonitor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdatePerformanceMonitor) Show() PerformanceMonitor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return PerformanceMonitor(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *UpdatePerformanceMonitor) MutateShow(n PerformanceMonitor) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func UpdatePerformanceMonitorStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UpdatePerformanceMonitorAddShow(builder *flatbuffers.Builder, show PerformanceMonitor) {
	builder.PrependByteSlot(0, byte(show), 0)
}
func UpdatePerformanceMonitorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
