// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Ping request message
type PingRequestT struct {
	Cookie uint64 `json:"cookie"`
}

func (t *PingRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	PingRequestStart(builder)
	PingRequestAddCookie(builder, t.Cookie)
	return PingRequestEnd(builder)
}

func (rcv *PingRequest) UnPackTo(t *PingRequestT) {
	t.Cookie = rcv.Cookie()
}

func (rcv *PingRequest) UnPack() *PingRequestT {
	if rcv == nil {
		return nil
	}
	t := &PingRequestT{}
	rcv.UnPackTo(t)
	return t
}

type PingRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPingRequest(buf []byte, offset flatbuffers.UOffsetT) *PingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PingRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPingRequest(buf []byte, offset flatbuffers.UOffsetT) *PingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PingRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PingRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PingRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PingRequest) Cookie() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PingRequest) MutateCookie(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func PingRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PingRequestAddCookie(builder *flatbuffers.Builder, cookie uint64) {
	builder.PrependUint64Slot(0, cookie, 0)
}
func PingRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
